# AI Configuration
ai:
  provider: "openai"  # or "anthropic"
  openai_api_key: "${OPENAI_API_KEY}"
  anthropic_api_key: "${ANTHROPIC_API_KEY}"
  model: "gpt-4"  # or "claude-2" for Anthropic

# Note Generation Settings
notes:
  template_path: "templates/note_template.txt"
  output_directory: "notes"
  date_format: "%Y-%m-%d"
  prefix_symbols:
    completed_today: "*"
    completed_later: "+"
    decided_against: "-"
    pending: ""

# Automation Settings
automation:
  enabled: true
  schedule_time: "09:00"  # 24-hour format
  timezone: "UTC"

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5
